# Generated by Django 2.2.dev20180610073152 on 2018-06-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AsyncTest',
        ),
    ]
